# Generated by Django 4.1.3 on 2022-12-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("waitlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waitlist",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Waitlist Entries",
            },
        ),
    ]
